version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev


  redis:
    image: redis:7
    container_name: redis_app
    command:
      --port 5370
    expose:
      - 5370


  celery_app_worker:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app_worker
    command: ['/fastapi_app/docker/celery.sh', 'worker', 'clear_db']
    depends_on:
      - redis


  celery_app_beat:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_beat
    command: [ '/fastapi_app/docker/celery.sh', 'beat', 'clear_db' ]
    depends_on:
      - redis


  celery_id_generator_worker:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_id_generator_worker
    command: [ '/fastapi_app/docker/celery.sh', 'worker', 'check_ids' ]
    depends_on:
      - redis
      - id_generator


  celery_id_generator_beat:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_id_generator_beat
    command: [ '/fastapi_app/docker/celery.sh', 'beat', 'check_ids' ]
    depends_on:
      - redis
      - id_generator


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ['/fastapi_app/docker/app.sh']
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis


  id_generator:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: id_generator
    command: ['/fastapi_app/docker/id_generator.sh']
    ports:
      - 7000:7000
    depends_on:
      - db
      - redis