"""create paste

Revision ID: 10697e3da209
Revises: 
Create Date: 2023-07-14 12:44:24.627035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10697e3da209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
    sa.Column('id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_delete', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paste')
    # ### end Alembic commands ###
