"""add paste

Revision ID: 2d8d855055cc
Revises: 7df6a5a4f62e
Create Date: 2023-07-11 15:47:00.182019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d8d855055cc'
down_revision = '7df6a5a4f62e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
    sa.Column('hash', sa.VARCHAR(length=8), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_delete', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.alter_column('post', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('paste')
    # ### end Alembic commands ###
