"""database creation

Revision ID: 7df6a5a4f62e
Revises: 
Create Date: 2023-07-10 23:53:19.491142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df6a5a4f62e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('hash', sa.VARCHAR(length=8), nullable=False),
                    sa.Column('url', sa.TEXT(), nullable=False),
                    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
                    sa.Column('date_delete', sa.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('hash')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
